### ISSUE TITLE
1.12.2 Mod Registry issue, doubles the mod's loading with certain launchers.

### ISSUE THREAD

**Issue by Ski-z** [KameiB/LocLoreMixin#1]
With certain mod launchers (GDLauncher for example), the mod is registered twice. This is a rare issue, but one I've only ever seen once before.

See: 
![image](https://github.com/KameiB/LocLoreMixin/assets/107653759/06008b15-efeb-4963-b732-004867e447d2)

When there is only one instance in the /mods folder. I have a friend who fixed his mod with this same issue, I can ask him how he fixed it.

**Comment by KameiB** [comment]
This is a screenshot of a different mod.
Can you test on a new instance with only my mod, to see if the problem happens?

**Comment by Ski-z** [comment]
Oops, so sorry, went to the wrong issues page!
